2011-04-29 15:48:11,193 DEBUG 4615 140182662313728 state():305 Traceback (most recent call last):
  File "/home/strzel_a/web2py/gluon/admin.py", line 145, in app_compile
    compile_application(folder)
  File "/home/strzel_a/web2py/gluon/compileapp.py", line 499, in compile_application
    compile_views(folder)
  File "/home/strzel_a/web2py/gluon/compileapp.py", line 273, in compile_views
    data = parse_template(file, path)
  File "/home/strzel_a/web2py/gluon/template.py", line 820, in parse_template
    return str(TemplateParser(text, context=context, path=path, lexers=lexers, delimiters=delimiters))
  File "/home/strzel_a/web2py/gluon/template.py", line 309, in __init__
    self.parse(text)
  File "/home/strzel_a/web2py/gluon/template.py", line 793, in parse
    self.extend(extend)
  File "/home/strzel_a/web2py/gluon/template.py", line 464, in extend
    text = self._get_file_text(filename)
  File "/home/strzel_a/web2py/gluon/template.py", line 440, in _get_file_text
    self._raise_error('Unable to open included view file: ' + filepath)
  File "/home/strzel_a/web2py/gluon/template.py", line 412, in _raise_error
    raise restricted.RestrictedError(self.name, self.text, message)
RestrictedError

